server:
  port: 9000
logging:
  level:
    security: DEBUG
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/keycloak_db
    username: udp
    password: udp
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
keycloak:
  auth-server-url: http://localhost:8080/ # URL of the Keycloak server
  realm: test-realm
  resource: test-client #client in keycloak
  credentials:
    secret: wREVcIQvOSPUbPfOIWNTGVpO3NITCZzL #secret of client
---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
      url: jdbc:h2:mem:testdb
      username: sa
      password: sa
      driver-class-name: org.h2.Driver
  jpa:
      database-platform: org.hibernate.dialect.H2Dialect