server:
  port: 8080
logging:
  level:
    security: DEBUG
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/udp
    username: udp
    password: udp
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
